version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  pg_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./storage/postgres/migrations:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onelab_db
      - POSTGRES_USER=onelab
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onelab -d onelab_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  migration:
    image: migrate/migrate
    command: -path /migrations/ -database 'postgres://onelab:qwerty@postgres:5432/onelab_db?sslmode=disable' up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage/postgres/migrations:/migrations/
    networks:
      - internal


  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    environment:
      - APP_MODE=dev
      - JWT_KEY=qwerty
      - TZ=Asia/Almaty
      - DB_HOST=postgres
      - DB_NAME=onelab_db
      - DB_USER=onelab
      - DB_PASSWORD=qwerty
      - DB_PORT=5432
    networks:
      - internal
    depends_on:
      - postgres
      - migration
      - redis

  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379:6379"